# AVS Configuration

[avs]
port = 3000
ws_port = 3001
bind_address = "0.0.0.0"

[solana]
rpc_url = "${SOLANA_RPC_URL}"
ws_url = "${SOLANA_WS_URL}"

[cambrian]
poa_name = "${CAMBRIAN_POA_NAME}"
admin_key_path = "/app/avs-wallet.json" 