x-environment: &default-env
  NODES: ${NODES:-3}
  BASE_PORT: ${BASE_PORT:-9000}
  RPC_PORT: ${RPC_PORT:-8899}
  WS_PORT: ${WS_PORT:-8900}
  FAUCET_PORT: ${FAUCET_PORT:-9910}
  API_PORT: ${API_PORT:-3000}
  RUST_LOG: ${RUST_LOG:-info}

services:
  solana-validator:
    image: validator-image
    platform: linux/amd64
    container_name: solana-validator
    volumes:
      - ./config/validator:/root/.config/solana/cli
      - ./config/geyser:/root/config/geyser
      - ./data/solana:/root/data/solana
      - geyser-plugin:/root/plugins
    ports:
      - "${RPC_PORT:-8899}:8899"
      - "${WS_PORT:-8900}:8900"
      - "${FAUCET_PORT:-9900}:9900"
    environment:
      - NODE_LOG_LEVEL=${LOG_LEVEL:-info}
    command: [
      "solana-test-validator",
      "--ledger", "/root/data/solana",
      "--faucet-sol", "200000000",
      "--limit-ledger-size", "50000000",
      "--geyser-plugin-config", "/root/config/geyser/plugin-config.json",
      "--rpc-port", "8899",
      "--quiet"
    ]
    depends_on:
      geyser-plugin:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8899 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - windexer-network

  geyser-plugin:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.geyser
    container_name: geyser-plugin
    volumes:
      - geyser-plugin:/app
      - ../../data/geyser:/app/data/geyser
    environment:
      - RUST_LOG=${RUST_LOG:-info}
    networks:
      - windexer-network

  # Node-0 is defined in the main file as it's always required
  node-0:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-node-0
    volumes:
      - ../../data/node_0:/app/data/node_0
    ports:
      - "${BASE_PORT}:9000"
      - "${BASE_PORT_PLUS_ONE:-10001}:10001"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - SOLANA_RPC_URL=http://solana-validator:8899
      - SOLANA_WS_URL=ws://solana-validator:8900
    command: node --index 0 --base-port 9000 --enable-tip-route
    networks:
      - windexer-network
    depends_on:
      solana-validator:
        condition: service_healthy

  # Postgres database
  postgres:
    image: postgres:15
    container_name: windexer-postgres
    environment:
      - POSTGRES_USER=windexer
      - POSTGRES_PASSWORD=windexer
      - POSTGRES_DB=windexer
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - windexer-network
    restart: unless-stopped

  # Data generator
  data-generator:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-data-generator
    volumes:
      - ../../scripts:/app/scripts
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - SOLANA_RPC_URL=http://solana-validator:8899
      - SOLANA_RPC_PORT=8899
    command: >
      bash -c "
        sleep 30 &&
        echo 'Generating sample data...' &&
        KEYPAIR_PATH=/app/examples/typescript/payer-keypair.json /app/scripts/test-scripts/generate-data.sh
      "
    networks:
      - windexer-network
    depends_on:
      solana-validator:
        condition: service_healthy
      node-0:
        condition: service_started

  # API Server
  api-server:
    container_name: api-server
    image: ${DOCKER_REPO:-anzaxyz}/windexer-api:${VERSION:-latest}
    build:
      context: ../../
      dockerfile: deployment/docker/api.Dockerfile
      args:
        CARGO_BUILD_ARGS: --release
    environment:
      <<: *default-env
      API_PORT: ${API_PORT:-3000}
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      solana-validator:
        condition: service_healthy
      node-0:
        condition: service_started
    restart: unless-stopped
    networks:
      - windexer-network

volumes:
  geyser-plugin:
  postgres-data:

networks:
  windexer-network:
    driver: bridge
