services:
  solana-validator:
    image: anzaxyz/agave:v2.2.0
    platform: linux/amd64
    container_name: solana-validator
    volumes:
      - ../../data/validator:/data
      - ../../config/geyser:/config/geyser
      - geyser-plugin:/app
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9910:9910"
    environment:
      - RUST_LOG=info
    command: >
      solana-test-validator
      --rpc-port 8899
      --geyser-plugin-config /config/geyser/windexer-geyser-config.json
      --reset
      --faucet-port 9910
      --bind-address 0.0.0.0
      --no-bpf-jit
    depends_on:
      - geyser-plugin
    networks:
      - windexer-network

  geyser-plugin:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.geyser
    container_name: geyser-plugin
    volumes:
      - geyser-plugin:/app
      - ../../data/geyser:/app/data/geyser
    environment:
      - RUST_LOG=info
    networks:
      - windexer-network

  # Start nodes (matching NODES=3 in Makefile)
  node-0:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-node-0
    volumes:
      - ../../data/node_0:/app/data/node_0
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUST_LOG=info
      - SOLANA_RPC_URL=http://solana-validator:8899
      - SOLANA_WS_URL=ws://solana-validator:8900
    command: node --index 0 --base-port 9000 --enable-tip-route
    networks:
      - windexer-network
    depends_on:
      - solana-validator

  node-1:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-node-1
    volumes:
      - ../../data/node_1:/app/data/node_1
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      - RUST_LOG=info
      - SOLANA_RPC_URL=http://solana-validator:8899
      - SOLANA_WS_URL=ws://solana-validator:8900
    command: node --index 1 --base-port 9000 --enable-tip-route
    networks:
      - windexer-network
    depends_on:
      - node-0

  node-2:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-node-2
    volumes:
      - ../../data/node_2:/app/data/node_2
    ports:
      - "9200:9000"
      - "9201:9001"
    environment:
      - RUST_LOG=info
      - SOLANA_RPC_URL=http://solana-validator:8899
      - SOLANA_WS_URL=ws://solana-validator:8900
    command: node --index 2 --base-port 9000 --enable-tip-route
    networks:
      - windexer-network
    depends_on:
      - node-0

  indexer-1:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-indexer-1
    volumes:
      - ../../data/indexer_1:/app/data/indexer_1
    ports:
      - "10001:10001"
    environment:
      - RUST_LOG=info
      - SOLANA_RPC_URL=http://solana-validator:8899
    command: indexer --index 1 --bootstrap-peers node-0:9000
    networks:
      - windexer-network
    depends_on:
      - node-0

  indexer-2:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-indexer-2
    volumes:
      - ../../data/indexer_2:/app/data/indexer_2
    ports:
      - "10002:10002"
    environment:
      - RUST_LOG=info
      - SOLANA_RPC_URL=http://solana-validator:8899
    command: indexer --index 2 --bootstrap-peers node-1:9000
    networks:
      - windexer-network
    depends_on:
      - node-1

  postgres:
    image: postgres:15
    container_name: windexer-postgres
    environment:
      - POSTGRES_USER=windexer
      - POSTGRES_PASSWORD=windexer
      - POSTGRES_DB=windexer
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - windexer-network
    restart: unless-stopped

  # Data generator using scripts from Makefile
  data-generator:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-data-generator
    volumes:
      - ../../scripts:/app/scripts
    environment:
      - RUST_LOG=info
    command: >
      bash -c "
        sleep 30 &&
        echo 'Generating sample data...' &&
        /app/scripts/test-scripts/demo-interact.sh
      "
    networks:
      - windexer-network
    depends_on:
      - indexer-1
      - indexer-2
      - solana-validator

volumes:
  geyser-plugin:
  postgres-data:

networks:
  windexer-network:
    driver: bridge
