x-environment: &default-env
  NODES: ${NODES:-3}
  BASE_PORT: ${BASE_PORT:-9000}
  RPC_PORT: ${RPC_PORT:-8999}
  WS_PORT: ${WS_PORT:-8900}
  FAUCET_PORT: ${FAUCET_PORT:-9910}
  RUST_LOG: ${RUST_LOG:-info}

services:
  solana-validator:
    image: anzaxyz/agave:v2.2.0
    platform: linux/amd64
    container_name: solana-validator
    volumes:
      - ../../data/validator:/data
      - ../../config/geyser:/config/geyser
      - geyser-plugin:/app
    ports:
      - "${RPC_PORT}:8999"
      - "${WS_PORT}:8900"
      - "${FAUCET_PORT}:9910"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
    command: >
      solana-test-validator
      --rpc-port 8999
      --geyser-plugin-config /config/geyser/windexer-geyser-config.json
      --reset
      --faucet-port 9910
      --bind-address 0.0.0.0
      --no-bpf-jit
    depends_on:
      - geyser-plugin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8999"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - windexer-network

  geyser-plugin:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.geyser
    container_name: geyser-plugin
    volumes:
      - geyser-plugin:/app
      - ../../data/geyser:/app/data/geyser
    environment:
      - RUST_LOG=${RUST_LOG:-info}
    networks:
      - windexer-network

  # Node-0 is defined in the main file as it's always required
  node-0:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-node-0
    volumes:
      - ../../data/node_0:/app/data/node_0
    ports:
      - "${BASE_PORT}:9000"
      - "${BASE_PORT_PLUS_ONE:-9001}:9001"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - SOLANA_RPC_URL=http://solana-validator:8999
      - SOLANA_WS_URL=ws://solana-validator:8900
    command: node --index 0 --base-port 9000 --enable-tip-route
    networks:
      - windexer-network
    depends_on:
      solana-validator:
        condition: service_healthy

  # Postgres database
  postgres:
    image: postgres:15
    container_name: windexer-postgres
    environment:
      - POSTGRES_USER=windexer
      - POSTGRES_PASSWORD=windexer
      - POSTGRES_DB=windexer
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - windexer-network
    restart: unless-stopped

  # Data generator
  data-generator:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-data-generator
    volumes:
      - ../../scripts:/app/scripts
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - SOLANA_RPC_URL=http://solana-validator:8999
      - SOLANA_RPC_PORT=8999
    command: >
      bash -c "
        sleep 30 &&
        echo 'Generating sample data...' &&
        KEYPAIR_PATH=/app/examples/typescript/payer-keypair.json /app/scripts/test-scripts/generate-data.sh
      "
    networks:
      - windexer-network
    depends_on:
      solana-validator:
        condition: service_healthy
      node-0:
        condition: service_started

volumes:
  geyser-plugin:
  postgres-data:

networks:
  windexer-network:
    driver: bridge
