version: '3.8'

services:
  solana-validator:
    image: solanalabs/solana:v2.2
    container_name: solana-validator
    volumes:
      - ./data/validator:/data
      - ./config/geyser:/config/geyser
      - geyser-plugin:/app
    ports:
      - "8899:8899"
      - "8900:8900"
      - "8001:8001"
      - "8002:8002"
    environment:
      - RUST_LOG=info
    command: >
      solana-test-validator
      --rpc-port 8899
      --geyser-plugin-config /config/geyser/windexer-geyser-config.json
      --reset
      --no-bpf-jit
    depends_on:
      - geyser-plugin
    networks:
      - windexer-network

  geyser-plugin:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.geyser
    container_name: geyser-plugin
    volumes:
      - geyser-plugin:/app
      - ./data/geyser:/app/data/geyser
    environment:
      - RUST_LOG=info
    networks:
      - windexer-network

  node-1:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-node-1
    volumes:
      - ./data/node_1:/app/data/node_1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUST_LOG=info
    command: node --index 1 --base-port 9000 --enable-tip-route
    networks:
      - windexer-network
    depends_on:
      - solana-validator

  node-2:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-node-2
    volumes:
      - ./data/node_2:/app/data/node_2
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      - RUST_LOG=info
    command: node --index 2 --base-port 9000 --enable-tip-route
    networks:
      - windexer-network
    depends_on:
      - node-1

  indexer-1:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-indexer-1
    volumes:
      - ./data/indexer_1:/app/data/indexer_1
    ports:
      - "10001:10001"
    environment:
      - RUST_LOG=info
    command: indexer --index 1 --bootstrap-peers node-1:9000
    networks:
      - windexer-network
    depends_on:
      - node-1

  indexer-2:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-indexer-2
    volumes:
      - ./data/indexer_2:/app/data/indexer_2
    ports:
      - "10002:10002"
    environment:
      - RUST_LOG=info
    command: indexer --index 2 --bootstrap-peers node-2:9000
    networks:
      - windexer-network
    depends_on:
      - node-2

  data-generator:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.node
    container_name: windexer-data-generator
    environment:
      - RUST_LOG=info
    command: >
      bash -c "
        sleep 30 &&
        echo 'Generating sample data...' &&
        ./scripts/generate-data.sh
      "
    networks:
      - windexer-network
    depends_on:
      - indexer-1
      - indexer-2
      - solana-validator

volumes:
  geyser-plugin:

networks:
  windexer-network:
    driver: bridge
